apiVersion: tekton.dev/v1beta1
kind: Task

metadata:
  name: hugo

spec:
  workspaces:
    - name: work-dir

  results:
    - name: output
      description: generated static site

  steps:
    - name: build
      image: hugomods/hugo:0.122.0
      script: |
        cd $(workspaces.work-dir.path)
        hugo version
        hugo mod get -u
        hugo mod graph
        hugo config
        hugo
        printf "%s" $(workspaces.work-dir.path) | tee /tekton/results/output
